services:
  n8n:
    container_name: n8n_dev
    image: docker.n8n.io/n8nio/n8n:${N8N_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data_dev:/home/node/.n8n
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678

      # For Task runners
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_AUTH_TOKEN=verysecrettoken
      - N8N_NATIVE_PYTHON_RUNNER=true

  task-runners:
    container_name: n8n_runners_dev
    build:
      context: ./task_runners
      args:
        - N8N_VERSION=${N8N_VERSION:-latest}
    restart: unless-stopped
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n_dev:5679
      - N8N_RUNNERS_AUTH_TOKEN=verysecrettoken
      # optional: keep runners warm in dev (less startup delay)
      - N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT=0
    depends_on:
      - n8n
